### ISSUE TITLE
Fix Deletion of MeshSync Resources

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshsync#100]
**Description**

**Expected Behavior**

**Screenshots**

                                                                                                                       
### Contributor Resources

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- See the [Contributing to Meshery.io Website](https://github.com/layer5io/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- See Meshery site designs in this [Figma designfile](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=110%3A1). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

**Comment by leecalcote** [comment]
@utkarsh-pro I'm creating this issue from a previous note taken about synchronization issues in removing stale resources. Are you able to expound on the issue's description? take it on?

**Comment by utkarsh-pro** [comment]
Yes @leecalcote. I am assigning this issue to myself.

**Comment by manav1403** [comment]
Hey, @utkarsh-pro are you on it still?

**Comment by utkarsh-pro** [comment]
Hi, @manav1403 unfortunately I have been severely sick for past few days so I haven't been able to focus here yet although **I do intend to**, If this interests you, please take this up.

// @leecalcote

**Comment by leecalcote** [comment]
Ugh. I'm very sorry to hear this, @utkarsh-pro. I hope that you're feeling better soon. 🤒
