### ISSUE TITLE
Upgrade to Golang 1.17, latest MeshKit and Meshery Operator

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshsync#106]
**Current Behavior**
The golang version and key dependencies need upgraded here.

---
**Resources**

**Alternatives / Additional Context**

### Contributor Resources

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- See the [Contributing to Meshery.io Website](https://github.com/layer5io/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- See Meshery site designs in this [Figma designfile](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=110%3A1). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

**Comment by MUzairS15** [comment]
Closing this issue, fixed in https://github.com/meshery/meshsync/pull/109
