### ISSUE TITLE
[Docs] Add Discuss Shield to MeshSync Readme

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshsync#139]
**Desired Behavior**
Use the same discuss shield from meshery/meshery's readme.

<img width="890" alt="Screen Shot 2022-07-14 at 6 23 31 PM" src="https://user-images.githubusercontent.com/7570704/179117456-b9067e3a-2164-4c4c-8105-e4090f2e779a.png">

### Contributor Resources

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- See the [Contributing to Meshery.io Website](https://github.com/layer5io/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- See Meshery site designs in this [Figma designfile](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=110%3A1). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

**Comment by bhavyastar** [comment]
Hey @leecalcote, 
I would like to work on this issue, please assign this issue to me. Happy to take that issue 😀
