### ISSUE TITLE
[Readme] Add meshery logo to the readme

### ISSUE THREAD

**Issue by legendarykamal** [meshery/meshsync#150]
**Current State:**

No meshery logo in readme.

**Desired State:**

Add a meshery logo by taking reference from github.com/meshery/meshery and make it match suitably in dark and light mode.

---
**Contributor Resources**
- [Meshery documentation site](https://docs.meshery.io/)
- [Meshery documentation source](https://github.com/meshery/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by UtkarshMishra12** [comment]
I want to work on this issue. Can you please assign it to me? @legendarykamal 
 Also,I need to add the logo in meshery.io Repo?

**Comment by legendarykamal** [comment]
here you go :100: 

no in mesh sync

**Comment by UtkarshMishra12** [comment]
So I can take the exact functionality from this  github.com/meshery/meshery  (Logo in Dark & Light Mode)and add the logo to it, by replacing it with the current one.

**Comment by nik132-eng** [comment]
If this problem is still not resolved, may I bring it up? for hacktoberfest

**Comment by UtkarshMishra12** [comment]
Hey @nik132-eng  PR has been raised just waiting for its approval.
