### ISSUE TITLE
Issue Template Updates for Figma link

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshsync#210]
#### Current Behavior
The project's current issue templates are missing an open invitation link where new contributors can join the community's Figma team and view user interface designs and other UX projects.

#### Desired Behavior
Each template that has a reference to Figma in its resources section should an invite link added.

#### Implementation

In each [issue template](../blob/master/.github/ISSUE_TEMPLATE/) that refers to Figma, replace the current line referring to Figma with this line:

```
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)```
```
#### Acceptance Tests
1. All references to Figma include the "open invite" link.

### Contributor Resources

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- See the [Contributing to Meshery.io Website](https://github.com/layer5io/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- See Meshery site designs in this [Figma designfile](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=110%3A1). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

**Comment by yashchaddha** [comment]
Hi @leecalcote I would like to contribute on this. Can i please get assigned to this?

**Comment by aryanas159** [comment]
I would also like to collaborate with @yashchaddha, can I be assigned to this, please.

**Comment by thisiskaransgit** [comment]
Closing the issue as completed via #212
