### ISSUE TITLE
Support Persistent Volumes

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshsync#215]
**Current Behavior**
MeshSync doesn't discover this resource type.

**Implementation**
Add support for discovering this Kubernetes resource type. Do the same thing that was done here - https://github.com/meshery/meshsync/commit/1b640b8cbfd6ffefc0896de8fc1ac2a6bd284822, but for `persistent volumes`

### Contributor Resources

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- See the [Contributing to Meshery.io Website](https://github.com/layer5io/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- See [Meshery site designs](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=110%3A1) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9). 
- Fill-in a [Community Member Form](https://layer5.io/newcomer) and join the [Community Slack](http://slack.meshery.io) for access.

**Comment by VaibhavMalik4187** [comment]
@leecalcote Can I give it a try?

**Comment by kituuu** [comment]
Can i try?

**Comment by theBeginner86** [comment]
We already have support for Persistent Volumes. Was added in this PR https://github.com/meshery/meshsync/pull/120

<img width="1532" alt="Screenshot 2023-08-17 at 8 28 43 PM" src="https://github.com/meshery/meshsync/assets/73700530/e8aae18c-fc6d-4662-94b6-93077b995e8a">

**Comment by leecalcote** [comment]
Thank you, @theBeginner86
