### ISSUE TITLE
Support Persistent Volume Claims

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshsync#216]
**Current Behavior**
MeshSync doesn't discover this resource type.

**Implementation**
Add support for discovering this Kubernetes resource type. Do the same thing that was done here - https://github.com/meshery/meshsync/commit/1b640b8cbfd6ffefc0896de8fc1ac2a6bd284822, but for `persistentvolumeclaims`

### Contributor Resources

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- See the [Contributing to Meshery.io Website](https://github.com/layer5io/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- See [Meshery site designs](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=110%3A1) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9). 
- Fill-in a [Community Member Form](https://layer5.io/newcomer) and join the [Community Slack](http://slack.meshery.io) for access.

**Comment by VaibhavMalik4187** [comment]
@leecalcote This one is similar to #215, am I allowed to work on both at the same time?

**Comment by Aritra8438** [comment]
You can add me i the queue @leecalcote.
Or if you wish, I can work on parallel.

**Comment by leecalcote** [comment]
@VaibhavMalik4187, on a separate note, pop over your email address in Slack, so that I can send you an example of open challenges with changes recently made to the release, workflow and email notifications.

**Comment by leecalcote** [comment]
@VaibhavMalik4187, yes, knocking out both in one swoop makes sense.

**Comment by leecalcote** [comment]
Will someone also open an issue to document the build instructions for MeshSync? This will ideally include the enhancement to use this standard Makefile includes that we have in each of the other repos for an improved make command DevEx? // @nebula-aac

**Comment by leecalcote** [comment]
The resource type is literally called `endpoints` - https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.26/#endpoints-v1-core

**Comment by leecalcote** [comment]
@Aritra8438 open an issue, please.

**Comment by Aritra8438** [comment]
Sure @Lee.
Few endpoints will be ConfigMap and Statefulset?

Are they supported by meshsync?
I'm opening issue for them.

**Comment by leecalcote** [comment]
Endpoints are for Services. Stop thinking "API Endpoint" and start thinking "Kubernetes Resource". The resource name is `Endpoint` just like `ConfigMap` and `Pod` and so on.

**Comment by Aritra8438** [comment]
Oh, I had no idea. Sorry sorry @leecalcote.

**Comment by theBeginner86** [comment]
We already have support for Persistent Volume Claims. Was added in this PR https://github.com/meshery/meshsync/pull/120


<img width="1532" alt="Screenshot 2023-08-17 at 8 28 37 PM" src="https://github.com/meshery/meshsync/assets/73700530/99551055-eeae-45f1-b95d-bcd0091c3dbb">

**Comment by leecalcote** [comment]
Uh-oh, I missed this. @VaibhavMalik4187, my apologies, let's go ahead and close this, acknowledging that most of the rest of the Kubernetes API types should be added, so new issues can be opened...
