### ISSUE TITLE
Support Ingresses

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshsync#217]
**Current Behavior**
MeshSync doesn't discover this resource type.

**Implementation**
Add support for discovering this Kubernetes resource type. Do the same thing that was done here - https://github.com/meshery/meshsync/commit/1b640b8cbfd6ffefc0896de8fc1ac2a6bd284822, but for `ingresses`

### Contributor Resources

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- See the [Contributing to Meshery.io Website](https://github.com/layer5io/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- See [Meshery site designs](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=110%3A1) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9). 
- Fill-in a [Community Member Form](https://layer5.io/newcomer) and join the [Community Slack](http://slack.meshery.io) for access.

**Comment by Vadiraj-Puranik** [comment]
@leecalcote  you can assign it to me and I will review this and make changes accordingly
Thanks

**Comment by leecalcote** [comment]
Sounds good. Thanks, @Vadiraj-Puranik
