### ISSUE TITLE
[Docs] Contributor build, run, test instructions for MeshSync

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshsync#220]
Document the build, run and test instructions for MeshSync.

Include the enhancement to use this standard Makefile includes that we have in each of the other repos for an improved make command DevEx? 

_Originally posted by @leecalcote in https://github.com/meshery/meshsync/issues/216#issuecomment-1681731491_

---
**Contributor Resources**
- [Meshery documentation site](https://docs.meshery.io/)
- [Meshery documentation source](https://github.com/meshery/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by leecalcote** [comment]
@VaibhavMalik4187? @Aritra8438?

**Comment by KiptoonKipkurui** [comment]
@leecalcote I have noticed issue has been closed but I feel some crucial information about how to run meshsync locally has been left out. After guidance from a community member , running meshsync locally requires running an instance of NATS server with certain ports exposed. I can happily document this, and even update the makefile to make this experience smooth for local development.

**Comment by leecalcote** [comment]
@KiptoonKipkurui you're right. The issue was auto-closed by GitHub.

**Comment by KiptoonKipkurui** [comment]
Cool @leecalcote  I will submit a PR with the documentation and updated makefile

**Comment by KiptoonKipkurui** [comment]
I am unable to link the PR to this issue but heres the PR link https://github.com/meshery/meshsync/pull/240

**Comment by leecalcote** [comment]
Here's what you're looking for - 
<img width="386" alt="Screenshot 2023-09-08 at 3 19 19 PM" src="https://github.com/meshery/meshsync/assets/7570704/6023510e-5fdb-4aa4-97eb-e5f5254aa236">
