### ISSUE TITLE
[Enhancement] Use Streaming Lists when available

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshsync#221]
### Current Behavior
MeshSync performs discovery of specific Kubernetes API types using watches and sharedInformers.

### Desired Behavior
Enhance MeshSync to use [Streaming Lists](https://kubernetes.io/docs/reference/using-api/api-concepts/#streaming-lists) when available in the managed Kubernetes cluster.

### Implementation:
1. Verify whether Streaming Lists are available. If so, use them.

### Acceptance Criteria
1. When Streaming Lists are not available, downgrade to current methodology.
1. Confirm that all of the same resource details are retrieved via Streaming Lists as are retrieved using the current methodology. 

### Contributor Resources

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- See the [Contributing to Meshery.io Website](https://github.com/layer5io/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- See [Meshery site designs](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=110%3A1) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9). 
- Fill-in a [Community Member Form](https://layer5.io/newcomer) and join the [Community Slack](http://slack.meshery.io) for access.

**Comment by leecalcote** [comment]
@Vadiraj-Puranik?

**Comment by Vadiraj-Puranik** [comment]
@leecalcote  sure on it , please assign

**Comment by leecalcote** [comment]
Oh, excellent. 👏

**Comment by leecalcote** [comment]
@Vadiraj-Puranik have a look - https://meshery.slack.com/archives/C010LFFGFFA/p1692376559484059 - you might be interested.

**Comment by Vadiraj-Puranik** [comment]
> I tossed in an update in the issue description.

@leecalcote  thanks I am reviewing currently , will reach out if require any further inputs/help

**Comment by leecalcote** [comment]
Good deal, @Vadiraj-Puranik. How's it coming along? What questions do you have?

**Comment by leecalcote** [comment]
@Vadiraj-Puranik I'll free-up this assignment so that progress on the issue can move forward. Don't hesitate to jump back in, should you return to work on it.

**Comment by KiptoonKipkurui** [comment]
@leecalcote please assign
