### ISSUE TITLE
Support `ConfigMaps`

### ISSUE THREAD

**Issue by Aritra8438** [meshery/meshsync#222]
**Description**
MeshSync doesn't discover this resource type.

**Expected Behavior**
Add support for discovering `ConfigMap` Kubernetes resource type. Do the same thing that was done here - https://github.com/meshery/meshsync/commit/1b640b8cbfd6ffefc0896de8fc1ac2a6bd284822, but for `ConfigMap`
                                                                                                                       
### Contributor Resources

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- See the [Contributing to Meshery.io Website](https://github.com/layer5io/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- See [Meshery site designs](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=110%3A1) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9). 
- Fill-in a [Community Member Form](https://layer5.io/newcomer) and join the [Community Slack](http://slack.meshery.io) for access.

**Comment by theBeginner86** [comment]
Unless I'm mistaken, ConfigMaps is too supported

<img width="1532" alt="Screenshot 2023-08-17 at 8 34 20 PM" src="https://github.com/meshery/meshsync/assets/73700530/c1a6a9b9-e95b-449d-be8b-f5d4d44c85df">

**Comment by Aritra8438** [comment]
Closing this, as meshsync already supports ConfigMaps.
