### ISSUE TITLE
[chore] Enhancement of MeshSync Discovery 

### ISSUE THREAD

**Issue by theBeginner86** [meshery/meshsync#233]
**Current Behavior**

Currently, every attributes of all resources is not being discovered by MeshSync.

For
Deployments:

<img width="896" alt="Screenshot 2023-08-29 at 7 55 02 PM" src="https://github.com/meshery/meshsync/assets/73700530/f72e8184-a4f2-458c-9c00-bcb9f1bc036b">

<img width="554" alt="Screenshot 2023-08-29 at 7 53 25 PM" src="https://github.com/meshery/meshsync/assets/73700530/dfdef26b-78c4-4665-a8fe-5441111d03f4">

For Namespace:

<img width="802" alt="Screenshot 2023-08-29 at 7 54 15 PM" src="https://github.com/meshery/meshsync/assets/73700530/0335e11b-8a1d-45ad-99ab-e9440844fedc">

**Desired Behavior**

Ensure MeshSync tracks all attributes of discovered objects. Eg for namspaces.

### Contributor Resources

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- See the [Contributing to Meshery.io Website](https://github.com/layer5io/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- See [Meshery site designs](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=110%3A1) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9). 
- Fill-in a [Community Member Form](https://layer5.io/newcomer) and join the [Community Slack](http://slack.meshery.io) for access.

**Comment by theBeginner86** [comment]
FYI @Aritra8438 @VaibhavMalik4187

**Comment by VaibhavMalik4187** [comment]
@theBeginner86 I need some help here, do you mind sharing some documentation related to the codebase structure?

**Comment by KiptoonKipkurui** [comment]
@theBeginner86 I have been looking into this issue, and I would like some clarification on whats the desired behavior in terms of an apples to apples comparison i.e either current Deployment To Desired Deployment object or current Namespace to desired Namespace object attributes.
I looked at the unstructured object returned being converted in `model_converter.go` at runtime and all configuration under the spec field for both Deployments and Namespaces  were captured as the attributes. The Namespace object had only the finalizer attribute  under the spec field. In comparing a Deployment object to a Namespace object, it may look like the Deployment object has more attributes than the Namespace object while in reality the Namespace object has few/one configured attribute. 
I would like your clarification on this to enable me help out on the issue.

**Comment by theBeginner86** [comment]
> @theBeginner86 I have been looking into this issue, and I would like some clarification on whats the desired behavior in terms of an apples to apples comparison i.e either current Deployment To Desired Deployment object or current Namespace to desired Namespace object attributes.
> I looked at the unstructured object returned being converted in `model_converter.go` at runtime and all configuration under the spec field for both Deployments and Namespaces were captured as the attributes. The Namespace object had only the finalizer attribute under the spec field. In comparing a Deployment object to a Namespace object, it may look like the Deployment object has more attributes than the Namespace object while in reality the Namespace object has few/one configured attribute.
> I would like your clarification on this to enable me help out on the issue.

I see. Thanks for taking a look.
I was thinking that we had some one off condition that was just looking for labels for resources of Deployment type. But after looking at your comment and this part of the Namespace [spec](https://github.com/kubernetes/api/blob/master/core/v1/types.go#L5774) It looks like we might have to augment our discovery logic a bit.
I wonder if we could use this [getLabels](https://github.com/kubernetes/apimachinery/blob/master/pkg/api/meta/meta.go#L309) function from [kubernetes/apimachinery](https://github.com/kubernetes/apimachinery)

> The original ask was to update our existing MeshSync discovery pipeline to ensure that more metadata is available for every Kubernetes resource discovered by MeshSync.
So, in the screenshot above I was giving an example of how MeshSync is aware of labels that are assigned to a Deployment but we currently are not tracking that for most of other resources, like Namespace in the above example.

**Comment by KiptoonKipkurui** [comment]
@theBeginner86 Let me look into this and see how much more information about an object we can capture

**Comment by theBeginner86** [comment]
We can close this issue.
As I realized that I was querying wrong datable. The required information is already available in kubernetes_key_value table.

Reference:
![Screenshot 2023-11-17 at 5 42 21 PM](https://github.com/meshery/meshsync/assets/73700530/030fb182-add2-4aa5-a1a9-3c91fe9f14b5)


So by default we should be looking at kubernetes_key_value as for every discovered object the labels and annotation are are stored in that specific table.
