### ISSUE TITLE
[CI] add error codes utility runner workflow

### ISSUE THREAD

**Issue by DelusionalOptimist** [meshery/meshsync#79]
**Current Behaviour**
Error codes utility runner workflow is not present.

**Desired Behavious**
Add the error codes utility runner workflow.

**Instructions in https://github.com/meshery/meshery-linkerd/issues/213**

**Comment by Blakelist7** [comment]
@DelusionalOptimist I would like to assist with this issue :)

**Comment by DelusionalOptimist** [comment]
Sure @Blakelist7 : )

**Comment by metonymic-smokey** [comment]
@Blakelist7 could we work on this one together?

**Comment by Blakelist7** [comment]
Sure @metonymic-smokey

**Comment by DelusionalOptimist** [comment]
Super cool 😎
