### ISSUE TITLE
New MeshSync Releases not receiving current version number

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshsync#96]
**Description**
Related to issue #86, new MeshSync release numbers are not showing in the Meshery UI. Is this a MeshSync issue?

Linker flags might be missing in the build process.
                                                                                                                       
### Contributor Resources

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- See the [Contributing to Meshery.io Website](https://github.com/layer5io/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- See Meshery site designs in this [Figma designfile](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=110%3A1). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

**Comment by piyushsingariya** [comment]
I can see that linker flags are added to docker-compose, variables are being set, the viper is setting those values as ENV variables, but what I don't find is that ENV variable is being used somewhere. I mean we did set it but where are we using that value?

@warunicorn19 @sudo-NithishKarthik can you guys point me to the part in UI where we're trying to get the version of meshsync??

**Comment by leecalcote** [comment]
@MUzairS15 ...

**Comment by piyushsingariya** [comment]
I think it's a more helm-chart issue, we try to get the meshsync version from label of the resource, labels are empty hence no version being shown in the UI.

**Comment by MUzairS15** [comment]
> I think it's a more helm-chart issue, we try to get the meshsync version from label of the resource, labels are empty hence no version being shown in the UI.

 Yes, I checked this is the reason for version not showing up. There is no label field in crd resource for MeshSync and Broker.

**Comment by MUzairS15** [comment]
https://github.com/meshery/meshsync/pull/132
